import type { NewListing } from '../../src/types/listing';

// Robert's second batch of known meetups (ROB-68) — mostly SoCal rec
// centers/gyms he doesn't have first-hand schedule confirmation for, so
// cost and signup_required are genuinely unknown for several of these
// rather than guessed. Coordinates geocoded from the addresses he
// provided via Nominatim.
//
// Assumptions made while parsing the raw list (flag/fix via the admin
// edit dialog if any of these are wrong):
// - MVVC: no Type given — assumed 'indoor' (a club name with no
//   grass/beach indication, at a gym-typical street address).
// - East Anaheim Open Gym: address had no city/state — assumed Anaheim,
//   CA per the name.
// - "9pm-12pm" (MVVC) and "9pm-12am" (Ignite) read as crossing midnight;
//   left end_time null instead of guessing whether 12 meant noon or
//   midnight typo'd as "12pm".
export const moreListings: NewListing[] = [
  {
    name: 'Orange County Volleyball Hui @AIM',
    type: 'indoor',
    cost: 'paid',
    lat: 33.7588407,
    lng: -118.0907638,
    days_times: [{ day: 'mon', start_time: '20:00', end_time: null }],
    signup_required: true,
    external_link: 'https://heylo.group/roxys-orange-county-volleyball-hui',
    min_skill_level: null,
    equipment_supplied: null,
    notes: 'Easier if you show up with a team',
    visibility: 'public',
    photo_url: null,
    payment_types: '$10, cash only',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'The Great Pasadena Volleyball Club',
    type: 'grass',
    cost: 'free',
    lat: 34.159389,
    lng: -118.098292,
    days_times: [
      { day: 'sat', start_time: '15:30', end_time: null },
      { day: 'sun', start_time: '15:30', end_time: null },
    ],
    signup_required: false,
    external_link: 'https://www.meetup.com/volleyball-69/',
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Almansor Rec',
    type: 'indoor',
    cost: 'free',
    lat: 34.088687,
    lng: -118.1170641,
    days_times: [
      { day: 'sun', start_time: '17:00', end_time: '21:00' },
      { day: 'sat', start_time: '12:00', end_time: '16:00' },
    ],
    signup_required: false,
    external_link: null,
    min_skill_level: 'B',
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'East Anaheim Open Gym',
    type: 'indoor',
    cost: 'free',
    lat: 33.8686064,
    lng: -117.7487554,
    days_times: [{ day: 'fri', start_time: '09:00', end_time: '13:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Samueli Academy',
    type: 'indoor',
    cost: 'paid',
    lat: 33.7627545,
    lng: -117.9023887,
    days_times: [{ day: 'wed', start_time: '19:30', end_time: '23:30' }],
    signup_required: false,
    external_link: null,
    min_skill_level: 'BB',
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$5',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Calvary Church',
    type: 'indoor',
    cost: 'paid',
    lat: 33.7543383,
    lng: -117.8350986,
    days_times: [{ day: 'tue', start_time: '20:00', end_time: '23:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$5',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Garden Grove Rec Center',
    type: 'indoor',
    cost: 'paid',
    lat: 33.763128,
    lng: -117.9658775,
    days_times: [
      { day: 'wed', start_time: '18:00', end_time: '21:00' },
      { day: 'sat', start_time: '13:30', end_time: '16:30' },
    ],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$3',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Rancho Cucamonga Sports Center',
    type: 'indoor',
    cost: null,
    lat: 34.103459,
    lng: -117.5456036,
    days_times: [
      { day: 'tue', start_time: '15:00', end_time: '20:00' },
      { day: 'wed', start_time: '15:00', end_time: '20:00' },
      { day: 'sun', start_time: '13:00', end_time: '17:00' },
    ],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'MVVC',
    type: 'indoor',
    cost: 'paid',
    lat: 37.3889423,
    lng: -122.03223,
    days_times: [{ day: 'fri', start_time: '21:00', end_time: null }],
    signup_required: false,
    external_link: null,
    min_skill_level: 'BB',
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$15',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Ignite',
    type: 'indoor',
    cost: 'paid',
    lat: 33.9747088,
    lng: -117.6861818,
    days_times: [{ day: 'sun', start_time: '21:00', end_time: null }],
    signup_required: false,
    external_link: null,
    min_skill_level: 'BB',
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$7',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Lake Forest Rec Center',
    type: 'indoor',
    cost: 'paid',
    lat: 33.6648595,
    lng: -117.656201,
    days_times: [{ day: 'sun', start_time: '10:00', end_time: '14:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$5',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Brea Rec Center',
    type: 'indoor',
    cost: 'paid',
    lat: 33.9162565,
    lng: -117.8906643,
    days_times: [
      { day: 'sat', start_time: '16:00', end_time: '19:00' },
      { day: 'wed', start_time: '18:00', end_time: '21:00' },
    ],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$6',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Jerome Rec Center',
    type: 'indoor',
    cost: null,
    lat: 33.7374137,
    lng: -117.8987699,
    days_times: [{ day: 'fri', start_time: '12:00', end_time: '16:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Veterans Sports Complex',
    type: 'indoor',
    cost: null,
    lat: 33.8237119,
    lng: -118.281603,
    days_times: [{ day: 'fri', start_time: '17:00', end_time: '20:30' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'La Mirada',
    type: 'indoor',
    cost: 'paid',
    lat: 33.9025493,
    lng: -118.0090471,
    days_times: [{ day: 'wed', start_time: '20:30', end_time: null }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$5',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Santa Susana',
    type: 'indoor',
    cost: null,
    lat: 34.2729036,
    lng: -118.6939782,
    days_times: [
      { day: 'thu', start_time: '16:00', end_time: '20:00' },
      { day: 'mon', start_time: '09:00', end_time: '12:00' },
      { day: 'fri', start_time: '09:00', end_time: '12:00' },
    ],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
];
