import type { NewListing } from '../../src/types/listing';

// ROB-85 — parsed from Robert's San Diego open-gym tracking sheet
// (rows 2-76, i.e. everything above the sheet's own "Inactive
// locations:" section, which was deliberately excluded). Each venue
// that showed up on multiple days in the sheet is merged into one
// listing with multiple days_times entries, rather than one row per
// day. All of these are public rec-center/gym drop-in sessions, hence
// type: 'indoor' and equipment_supplied: true throughout (every row in
// the source sheet explicitly says nets are provided).
//
// The sheet's second section (rows ~50-73, everything from "Northern
// Open Gyms" through Hunt Park) carries its own disclaimer in the
// source — "hasn't been updated since April 2023" — carried through
// into each of those listings' notes here so it's visible to anyone
// reviewing them, not just buried in this comment.
//
// Skipped as duplicates of listings already in the DB (same address —
// not re-inserted, left as-is; flagged separately for Robert to merge
// schedule/cost differences manually if desired):
// - Calvary Chapel of Santa Ana (1010 N Tustin Ave) = existing "Calvary Church"
// - Garden Grove Sports and Recreation Center (13641 Deodara Dr) = existing "Garden Grove Rec Center"
// - Veterans Park/Sports Complex (22400 Moneta Ave, Carson) = existing "Veterans Sports Complex"
// - Lake Forest Recreation Center (28000 Ranch Pkwy) = existing "Lake Forest Rec Center" —
//   sheet shows Fri/Sat/Sun at $10/day; existing listing only has Sunday at $5
// - Bishop Mora Salesian High School (960 S Soto St, LA) = existing "Soto Volleyball" (same address)
//
// Skipped as not parseable into a single listing: UC San Diego (no
// fixed address/schedule, just a link to a page with "random
// timeslots"), and the standalone "more up-to-date LA/OC info" link row.
export const sdAndOcListings: NewListing[] = [
  {
    name: 'Coronado Community Center (South Side)',
    type: 'indoor',
    cost: 'paid',
    lat: 32.6767954,
    lng: -117.1716122,
    days_times: [
      { day: 'mon', start_time: '05:30', end_time: '15:00' },
      { day: 'wed', start_time: '05:30', end_time: '15:00' },
      { day: 'fri', start_time: '05:30', end_time: '19:00' },
      { day: 'sun', start_time: '12:15', end_time: '16:00' },
    ],
    signup_required: false,
    external_link: 'https://www.coronado.ca.us/330/Coronado-Community-Center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: '1 net available, room for 2',
    visibility: 'public',
    photo_url: null,
    payment_types: '$5 daily',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Coronado Community Center (Side B)',
    type: 'indoor',
    cost: 'paid',
    lat: 32.6767954,
    lng: -117.1716122,
    days_times: [{ day: 'wed', start_time: '10:00', end_time: '14:00' }],
    signup_required: false,
    external_link: 'https://www.coronado.ca.us/330/Coronado-Community-Center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: '1 net available, room for 2',
    visibility: 'public',
    photo_url: null,
    payment_types: '$5 daily',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Corky Smith Gymnasium (West Gym)',
    type: 'indoor',
    cost: 'free',
    lat: 33.142673,
    lng: -117.1659685,
    days_times: [
      { day: 'mon', start_time: '09:30', end_time: '12:30' },
      { day: 'wed', start_time: '09:30', end_time: '12:30' },
    ],
    signup_required: false,
    external_link: 'https://www.san-marcos.net/departments/parks-recreation/sports/gymnasium-programs-and-schedule',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Montevalle Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.656424,
    lng: -116.949287,
    days_times: [{ day: 'mon', start_time: '15:30', end_time: '19:00' }],
    signup_required: false,
    external_link: 'https://www.chulavistaca.gov/departments/parks-and-recreation/community-centers/montevalle-community-center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Doyle Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.865176,
    lng: -117.219751,
    days_times: [{ day: 'mon', start_time: '16:30', end_time: '20:30' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/doyle',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Balboa Park Activity Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.7266216,
    lng: -117.1477046,
    days_times: [
      { day: 'mon', start_time: '17:30', end_time: '20:30' },
      { day: 'wed', start_time: '17:30', end_time: '20:30' },
    ],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/bpac/',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Loma Verde Community Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.602399,
    lng: -117.0485829,
    days_times: [{ day: 'mon', start_time: '18:00', end_time: '20:00' }],
    signup_required: false,
    external_link: 'https://www.chulavistaca.gov/departments/parks-and-recreation/community-centers/loma-verde-aquatic-center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Pop-up open gym — schedule may vary, confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Spring Valley Gymnasium',
    type: 'indoor',
    cost: 'paid',
    lat: 32.7123953,
    lng: -117.0034923,
    days_times: [
      { day: 'mon', start_time: '19:00', end_time: '23:00' },
      { day: 'fri', start_time: '18:00', end_time: '23:00' },
    ],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Minors under 18 free with a signed parent liability waiver',
    visibility: 'public',
    photo_url: null,
    payment_types: '$2 daily or $15/month membership',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Parkway Community Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.6382677,
    lng: -117.0817874,
    days_times: [
      { day: 'tue', start_time: '18:00', end_time: '20:00' },
      { day: 'thu', start_time: '18:00', end_time: '20:00' },
    ],
    signup_required: false,
    external_link: 'https://www.chulavistaca.gov/departments/parks-and-recreation/community-centers/parkway-community-center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Carmel Mountain Ranch / Sabre Springs Recreation Center',
    type: 'indoor',
    cost: null,
    lat: 32.966814,
    lng: -117.091234,
    days_times: [{ day: 'tue', start_time: '12:00', end_time: '14:00' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/carmelsabre',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Pacific Highlands Ranch Recreation Center (East Gym)',
    type: 'indoor',
    cost: 'free',
    lat: 32.9600229,
    lng: -117.1868307,
    days_times: [
      { day: 'tue', start_time: '12:00', end_time: '15:45' },
      { day: 'fri', start_time: '13:45', end_time: '18:30' },
    ],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/pacifichighlandsranch',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Pacific Highlands Ranch Recreation Center (West Gym)',
    type: 'indoor',
    cost: 'free',
    lat: 32.9600229,
    lng: -117.1868307,
    days_times: [{ day: 'thu', start_time: '15:45', end_time: '17:15' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/pacifichighlandsranch',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Ocean Air Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.9279481,
    lng: -117.2170168,
    days_times: [
      { day: 'tue', start_time: '18:00', end_time: '19:45' },
      { day: 'sat', start_time: '11:00', end_time: '14:30' },
    ],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/oceanair',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'North Park Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.751318,
    lng: -117.134225,
    days_times: [
      { day: 'tue', start_time: '18:00', end_time: '19:45' },
      { day: 'sun', start_time: '12:00', end_time: '15:00' },
    ],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/northpark',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Renette Recreation Center',
    type: 'indoor',
    cost: 'paid',
    lat: 32.7831764,
    lng: -116.9684834,
    days_times: [
      { day: 'tue', start_time: '18:30', end_time: '21:00' },
      { day: 'thu', start_time: '18:30', end_time: '21:00' },
    ],
    signup_required: false,
    external_link: 'https://www.elcajon.gov/your-government/departments/recreation/recreation-centers/renette-recreation-center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: '18+ only',
    visibility: 'public',
    photo_url: null,
    payment_types: '$2 daily or $10 annual membership',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Golden Hill Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.7300663,
    lng: -117.1367331,
    days_times: [
      { day: 'wed', start_time: '11:00', end_time: '14:30' },
      { day: 'fri', start_time: '11:00', end_time: '14:30' },
    ],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/goldenhill',
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Small/limited participation',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Veterans Park Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.6148125,
    lng: -117.0234251,
    days_times: [{ day: 'wed', start_time: '16:00', end_time: '19:00' }],
    signup_required: false,
    external_link: 'https://www.chulavistaca.gov/departments/parks-and-recreation/community-centers/veterans-community-center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Nobel Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.8676389,
    lng: -117.1976396,
    days_times: [{ day: 'wed', start_time: '18:00', end_time: '20:45' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/nobel',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Mira Mesa Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.914486,
    lng: -117.140391,
    days_times: [{ day: 'wed', start_time: '18:00', end_time: '20:45' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/miramesa',
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Only some Wednesdays — confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Hillside Recreation Center',
    type: 'indoor',
    cost: 'paid',
    lat: 32.8063656,
    lng: -116.984479,
    days_times: [
      { day: 'wed', start_time: '19:00', end_time: '21:00' },
      { day: 'fri', start_time: '19:00', end_time: '21:00' },
    ],
    signup_required: false,
    external_link: 'https://www.elcajon.gov/your-government/departments/recreation/recreation-centers/hillside-community-center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: '18+ only',
    visibility: 'public',
    photo_url: null,
    payment_types: '$2 daily or $10 annual membership',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Bostonia Recreation Center',
    type: 'indoor',
    cost: 'paid',
    lat: 32.8093139,
    lng: -116.9331308,
    days_times: [
      { day: 'wed', start_time: '18:30', end_time: '21:00' },
      { day: 'fri', start_time: '18:30', end_time: '21:00' },
    ],
    signup_required: false,
    external_link: 'https://www.elcajon.gov/your-government/departments/recreation/recreation-centers/bostonia-community-center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: '$10-13 annual membership',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Black Mountain Multi-Purpose Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.9692682,
    lng: -117.1265081,
    days_times: [{ day: 'thu', start_time: '18:15', end_time: '20:45' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/blkmtn',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Standley Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.8510912,
    lng: -117.2103114,
    days_times: [{ day: 'thu', start_time: '18:00', end_time: '20:45' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/standley',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Church of Jesus Christ of Latter-Day Saints (Black Mountain Rd)',
    type: 'indoor',
    cost: 'free',
    lat: 32.9511777,
    lng: -117.1302294,
    days_times: [{ day: 'thu', start_time: '21:00', end_time: '00:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Church setting — please dress/act accordingly',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Tierrasanta Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.8268164,
    lng: -117.0821419,
    days_times: [{ day: 'fri', start_time: '12:00', end_time: '15:30' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/tierrasanta',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Stagecoach Community Center Gym',
    type: 'indoor',
    cost: null,
    lat: 33.0792328,
    lng: -117.2299252,
    days_times: [{ day: 'fri', start_time: '17:30', end_time: '20:00' }],
    signup_required: false,
    external_link: 'https://www.carlsbadca.gov/departments/parks-recreation/parks-community-centers/community-centers/open-play',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Church of Jesus Christ of Latter-Day Saints (Chula Vista)',
    type: 'indoor',
    cost: 'free',
    lat: 32.6450584,
    lng: -116.9959632,
    days_times: [{ day: 'fri', start_time: '20:00', end_time: '23:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Church setting — please dress/act accordingly',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'North Clairemont Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.8324022,
    lng: -117.1973999,
    days_times: [{ day: 'sat', start_time: '09:00', end_time: '12:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Camacho Recreation Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.668176,
    lng: -117.0840612,
    days_times: [{ day: 'sat', start_time: '09:00', end_time: '15:00' }],
    signup_required: false,
    external_link: 'https://www.nationalcityca.gov/government/community-services/programs/camacho-rec-center',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Hourglass Field Community Park (Miramar College, Bldg J-1)',
    type: 'indoor',
    cost: 'free',
    lat: 32.9090677,
    lng: -117.1243143,
    days_times: [{ day: 'sun', start_time: '10:00', end_time: '13:00' }],
    signup_required: false,
    external_link: 'https://www.sandiego.gov/park-and-recreation/centers/recctr/hourglass',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Twin Peaks Multi-Purpose Center',
    type: 'indoor',
    cost: 'free',
    lat: 32.9788365,
    lng: -117.0277047,
    days_times: [{ day: 'sun', start_time: '18:00', end_time: '21:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  // -- "Northern" LA/OC section — sheet flags this whole section as not
  // updated since April 2023, carried into each notes field below.
  {
    name: 'Los Angeles Police Academy',
    type: 'indoor',
    cost: 'free',
    lat: 34.0813573,
    lng: -118.24194,
    days_times: [{ day: 'mon', start_time: '19:00', end_time: '22:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Not verified since April 2023 — confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Moreno Valley Recreation/Conference Center',
    type: 'indoor',
    cost: null,
    lat: 33.9163559,
    lng: -117.2623424,
    days_times: [
      { day: 'wed', start_time: '17:00', end_time: '21:00' },
      { day: 'thu', start_time: '17:00', end_time: '21:00' },
    ],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Not verified since April 2023 — confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Walnut Gym',
    type: 'indoor',
    cost: 'paid',
    lat: 34.0253937,
    lng: -117.8453719,
    days_times: [{ day: 'wed', start_time: '18:00', end_time: '20:30' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Not verified since April 2023 — confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: '$5 daily',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Norton Recreation Center',
    type: 'indoor',
    cost: 'paid',
    lat: 34.1024381,
    lng: -117.2517715,
    days_times: [{ day: 'wed', start_time: '18:30', end_time: '21:30' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Not verified since April 2023 — confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: '$2 daily',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Church of Jesus Christ of Latter-Day Saints (Murrieta)',
    type: 'indoor',
    cost: 'free',
    lat: 33.5754644,
    lng: -117.182756,
    days_times: [{ day: 'wed', start_time: '20:30', end_time: '23:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Church setting — please dress/act accordingly. Not verified since April 2023.',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Chino Neighborhood Activity Center',
    type: 'indoor',
    cost: 'free',
    lat: 34.013601,
    lng: -117.691659,
    days_times: [{ day: 'thu', start_time: '17:00', end_time: '20:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Not verified since April 2023 — confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Herbert Hoover Middle School',
    type: 'indoor',
    cost: 'free',
    lat: 33.8398057,
    lng: -118.151464,
    days_times: [{ day: 'thu', start_time: '18:30', end_time: '21:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Not verified since April 2023 — confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'OC Resilient',
    type: 'indoor',
    cost: 'paid',
    lat: 33.7628507,
    lng: -117.9114913,
    days_times: [{ day: 'thu', start_time: '21:30', end_time: '01:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Confirm via Instagram @ocresilient before going. Not verified since April 2023.',
    visibility: 'public',
    photo_url: null,
    payment_types: '$10 daily',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Downtown Recreation Center',
    type: 'indoor',
    cost: 'paid',
    lat: 33.6413311,
    lng: -117.9227145,
    days_times: [{ day: 'fri', start_time: '18:00', end_time: '21:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Not verified since April 2023 — confirm before going',
    visibility: 'public',
    photo_url: null,
    payment_types: '$3-5 daily',
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Volitude Volleyball (Artesia High School)',
    type: 'indoor',
    cost: null,
    lat: 33.8445852,
    lng: -118.0746486,
    days_times: [{ day: 'fri', start_time: '19:00', end_time: '21:00' }],
    signup_required: true,
    external_link: 'https://www.volitudevolleyball.com/open-gym-1',
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Registration required before attending. Not verified since April 2023.',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Rendezvous Volleyball (The Draft)',
    type: 'indoor',
    cost: 'free',
    lat: 33.873382,
    lng: -117.5328766,
    days_times: [{ day: 'fri', start_time: '20:00', end_time: '23:00' }],
    signup_required: false,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Confirm via Instagram @rendezvous_volleyball before going. Not verified since April 2023.',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Hunt Park',
    type: 'indoor',
    cost: 'paid',
    lat: 33.9280453,
    lng: -117.4418356,
    days_times: [{ day: 'sun', start_time: '18:00', end_time: '20:00' }],
    signup_required: true,
    external_link: null,
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Intermediate/advanced players only. Must RSVP: (951) 317-8331. Not verified since April 2023.',
    visibility: 'public',
    photo_url: null,
    payment_types: '$12 daily or $35 monthly',
    team_required: null,
    submitted_by: null,
  },
];
