import type { NewListing } from '../../src/types/listing';

// Robert's known LA/SFV meetups — filled in for ROB-17 (M2). Coordinates
// geocoded from the addresses he provided via Nominatim.
export const seedListings: NewListing[] = [
  {
    name: 'NoHo Volleyball',
    type: 'grass',
    cost: 'free',
    lat: 34.1616496,
    lng: -118.3790724,
    days_times: [
      { day: 'thu', start_time: '16:30', end_time: null },
      { day: 'sat', start_time: '14:00', end_time: null },
      { day: 'sun', start_time: '15:00', end_time: null },
    ],
    signup_required: false,
    external_link: 'https://www.meetup.com/nohovolleyball/',
    min_skill_level: 'C',
    equipment_supplied: true,
    notes:
      "The grass is worn down so it's mostly dirt. Wear shoes! 6v6, tons of nets, no wait times. " +
      'Games run until sundown. Also see meetup.com/burbank-rec-club.',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Soto Volleyball',
    type: 'indoor',
    cost: 'paid',
    lat: 34.0324954,
    lng: -118.2158463,
    days_times: [],
    signup_required: true,
    external_link: 'https://www.meetup.com/la-indoor-volleyball-open-gym/',
    min_skill_level: null,
    equipment_supplied: true,
    notes: 'Schedule is sporadic — check Meetup for upcoming session times.',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'LAVO Womens',
    type: 'indoor',
    cost: 'paid',
    lat: 34.194028,
    lng: -118.363853,
    days_times: [{ day: 'mon', start_time: '19:45', end_time: null }],
    signup_required: true,
    external_link: 'https://www.meetup.com/playlavo/',
    min_skill_level: 'B',
    equipment_supplied: true,
    notes: 'Women only',
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'LAVO Advanced',
    type: 'indoor',
    cost: 'paid',
    lat: 34.0814684,
    lng: -118.3851616,
    days_times: [{ day: 'wed', start_time: '19:00', end_time: null }],
    signup_required: true,
    external_link: 'https://www.meetup.com/playlavo/',
    min_skill_level: 'BB',
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'LAVO Open',
    type: 'indoor',
    cost: 'paid',
    lat: 34.081685,
    lng: -118.3838004,
    days_times: [{ day: 'sun', start_time: null, end_time: null }],
    signup_required: true,
    external_link: 'https://www.meetup.com/playlavo/',
    min_skill_level: null,
    equipment_supplied: true,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Santa Barbara Beach Volleyball (SBBV)',
    type: 'beach',
    cost: 'free',
    lat: 34.4174158,
    lng: -119.6666264,
    days_times: [
      { day: 'sat', start_time: null, end_time: null },
      { day: 'sun', start_time: null, end_time: null },
    ],
    signup_required: false,
    external_link: 'https://www.meetup.com/santabarbara-volleyball',
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'West LA Beach Volleyball',
    type: 'beach',
    cost: 'free',
    lat: 34.0336978,
    lng: -118.5088948,
    days_times: [{ day: 'sat', start_time: '09:00', end_time: null }],
    signup_required: false,
    external_link: 'https://www.meetup.com/west-la-beach-volleyball',
    min_skill_level: null,
    equipment_supplied: null,
    notes: null,
    visibility: 'public',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
  {
    name: 'Good Vibes Volleyball',
    type: 'indoor',
    cost: 'paid',
    lat: 34.1312301,
    lng: -118.2634684,
    days_times: [
      { day: 'fri', start_time: null, end_time: null },
      { day: 'sat', start_time: null, end_time: null },
      { day: 'sun', start_time: null, end_time: null },
    ],
    signup_required: true,
    external_link: null,
    min_skill_level: 'B',
    equipment_supplied: true,
    notes: null,
    visibility: 'private',
    photo_url: null,
    payment_types: null,
    team_required: null,
    submitted_by: null,
  },
];
